language: node_js
node_js:
- 6.9.2
cache:
  directories:
  - node_modules
before_script:
- mkdir dist
- npm install
script:
- npm run build
deploy:
- provider: npm
- email: "guiseek@gmail.com"
- api_key: "$NPM_TOKEN"
  on:
  - branch: master