language: node_js
node_js:
  6.9.2
before_deploy:
  npm install
  npm run build
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "dist/bundle.js"
    - "dist/bundle.min.js"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true