language: node_js
node_js:
  6.9.2
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: exanokes
  repo: angular-facebook-factory
  target_branch: master
  on:
    branch: master
install:
  mkdir dist
before_script:
  npm install
script:
  npm run build