language: node_js
node_js:
  6.9.2
before_deploy:

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "dist/bundle.js"
    - "dist/bundle.min.js"
  skip_cleanup: true
  on:
    branch: master
install:
  mkdir dist
before_script:
  npm install
script:
  npm run build