language: node_js
node_js:
  6.9.2
install:
  - mkdir dist
  - npm install
before_deploy:
  - npm run build
deploy:
  - provider: pages
  - skip_cleanup: true
  - github_token: $GITHUB_TOKEN
  - local_dir: dist
  - target_branch: gh-pages
  on:
    - branch: master